version: "3.9"
services:
  reactapp:
    container_name: calculator-react-app
    build:
      context: ./calc-client
      dockerfile: Dockerfile-prod
    ports:
      - "8082:80"
    depends_on:
      - dotnetserver
  dotnetserver:
    container_name: calculator-dotnet-core
    build:
      context: ./calc-api/calc
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    container_name: calculator-sqlserver-db
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "C@lcP@55"
      ACCEPT_EULA: "Y"
    ports:
      - 1402:1433
