version: "3.9"
services:
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "C@lcP@55"
      ACCEPT_EULA: "Y"
    ports:
      - 1402:1433
